import { VoucherItem } from './types';

export const ACTIVE_VOUCHER_COUNT = 3;

export const VOUCHER_ITEMS: VoucherItem[] = [
  {
    id: '1',
    type: 'voucher',
    badge: 'VOUCHER',
    badgeTone: 'green',
    title: 'Giảm 50.000đ đơn từ 1.000.000đ',
    expiryLabel: 'Còn 3 ngày',
    description: 'Áp dụng cho tất cả sản phẩm',
    descriptionIcon: 'bag',
    actionLabel: 'Dùng ngay',
    tab: 'active',
  },
  {
    id: '2',
    type: 'voucher',
    badge: 'VOUCHER',
    badgeTone: 'green',
    title: 'Giảm 30.000đ đơn từ 700.000đ',
    expiryLabel: 'Còn 1 ngày',
    description: 'Dành cho đơn hàng vật tư nông nghiệp',
    descriptionIcon: 'leaf',
    actionLabel: 'Dùng ngay',
    tab: 'active',
  },
  {
    id: '3',
    type: 'service',
    badge: 'DỊCH VỤ',
    badgeTone: 'blue',
    title: 'Miễn phí tư vấn kỹ sư tại vườn',
    description: 'Tư vấn chuyên sâu, giải pháp phù hợp cho vườn của bạn',
    descriptionIcon: 'user',
    actionLabel: 'Xem chi tiết',
    specialLabel: 'Đặc biệt',
    tab: 'active',
  },
  {
    id: '4',
    type: 'voucher',
    badge: 'VOUCHER',
    badgeTone: 'green',
    title: 'Giảm 20.000đ đơn từ 500.000đ',
    expiryLabel: 'Còn 2 ngày',
    description: 'Ưu đãi sắp hết hạn',
    descriptionIcon: 'bag',
    actionLabel: 'Dùng ngay',
    tab: 'expiring',
  },
  {
    id: '5',
    type: 'voucher',
    badge: 'VOUCHER',
    badgeTone: 'green',
    title: 'Giảm 10.000đ đơn từ 300.000đ',
    description: 'Đã sử dụng tại cửa hàng',
    descriptionIcon: 'bag',
    actionLabel: 'Đã dùng',
    tab: 'used',
  },
];
